'use strict';
const $=id=>document.getElementById(id),storeKey='zhenhuan-gh-pages-v1';
let state=load(),current=0,jumping=false,timer=null,lastResult=null,posterBlob=null,posterUrl=null;
function load(){try{const s=JSON.parse(localStorage.getItem(storeKey));return {active:!!s?.active,used:Math.max(0,Number(s?.used)||0),answers:s?.answers||{},history:Array.isArray(s?.history)?s.history:[],fp:s?.fp,suffix:s?.suffix}}catch{return {active:false,used:0,answers:{},history:[]}}}
function save(){try{localStorage.setItem(storeKey,JSON.stringify(state))}catch{$('notice').textContent='浏览器暂时无法保存进度。请保持页面开启，并及时保存结果卡。'}}
function cancelJump(){clearTimeout(timer);jumping=false}
function show(id){cancelJump();['entry','lobby','quiz','result'].forEach(x=>$(x).classList.toggle('hidden',x!==id));if(id==='lobby')renderLobby();window.scrollTo(0,0)}
async function digest(s){if(!crypto.subtle)return s;const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s));return [...new Uint8Array(b)].map(n=>n.toString(16).padStart(2,'0')).join('')}
$('activateForm').onsubmit=async e=>{e.preventDefault();const v=$('code').value.trim().toUpperCase();if(!DATA.codes.includes(v)){$('entryMsg').textContent='这封入宫笺暂未识别，请检查授权码是否完整。';return}state.active=true;state.fp=await digest(v+'|'+navigator.userAgent);state.suffix=v.slice(-4);save();show('lobby')};
$('cast').innerHTML=DATA.characters.map(p=>`<figure><img loading="lazy" src="characters/${p.id}.jpg" alt="${p.name}"><figcaption>${p.name}</figcaption></figure>`).join('');
function renderLobby(){if(!state.active){show('entry');return}$('quotaText').textContent=`剩余 ${Math.max(0,10-state.used)} / 10 次 · 每一份旧小传都可随时重读`;$('start').textContent=Object.keys(state.answers).length?'继续未完成的测试':'开始我的24道问心题';$('resetDraft').hidden=!Object.keys(state.answers).length;$('history').replaceChildren();if(!state.history.length)$('history').textContent='你的第一份人物小传，将留在这里。';state.history.slice().reverse().forEach(r=>{const b=document.createElement('button');b.textContent=`${r.primary.name} · ${r.primary.subtitle}　${new Date(r.time).toLocaleDateString('zh-CN')}`;b.onclick=()=>renderResult(r);$('history').append(b)})}
function start(){if(state.used>=10){$('quotaText').textContent='10次测试已完成，仍可随时查看与保存已有结果。';return}current=DATA.questions.findIndex(q=>!state.answers[q.id]);if(current<0)current=0;show('quiz');renderQ()}
$('start').onclick=start;$('resetDraft').onclick=()=>{state.answers={};save();renderLobby()};$('quit').onclick=()=>{save();show('lobby')};$('prev').onclick=()=>{cancelJump();if(current>0){current--;renderQ()}};
function renderQ(){const q=DATA.questions[current];$('scene').textContent=q.scene;$('count').textContent=String(current+1).padStart(2,'0')+' / 24';const n=Object.keys(state.answers).length;$('bar').style.width=n/24*100+'%';$('progress').setAttribute('aria-valuenow',n);$('question').textContent=q.text;$('options').replaceChildren();q.options.forEach(o=>{const b=document.createElement('button');const selected=state.answers[q.id]===o.id;b.className='option'+(selected?' selected':'');b.setAttribute('aria-pressed',selected);b.innerHTML=`<b>${o.id}</b><span>${o.text}</span>`;b.onclick=()=>choose(q,o);$('options').append(b)});$('prev').disabled=current===0;$('qHint').textContent=current===23?'选择后生成你的人物小传':'选择后自动进入下一题';$('question').focus({preventScroll:true})}
function choose(q,o){if(jumping)return;jumping=true;state.answers[q.id]=o.id;save();renderQ();$('qHint').textContent='已记下你的选择';timer=setTimeout(()=>{jumping=false;if(current<23){current++;renderQ()}else submit()},420)}
function submit(){if(!state.active||state.used>=10){show('lobby');return}try{const raw=scores(state.answers),ranked=match(raw);const r={time:Date.now(),scores:raw.map(n=>Math.round(n/12*100)),primary:ranked[0].person,secondary:ranked[1].person,topMatches:ranked.slice(0,3).map(x=>({person:x.person,similarity:sim(raw,x.person)}))};state.used++;state.history.push(r);state.answers={};save();renderResult(r)}catch(e){$('qHint').textContent=e.message}}
function radarSvg(values){const xy=(i,r)=>[180+Math.cos(-Math.PI/2+i*Math.PI/3)*r,145+Math.sin(-Math.PI/2+i*Math.PI/3)*r];let s='<svg viewBox="0 0 360 300" role="img" aria-label="六维性格雷达图">';[.25,.5,.75,1].forEach(f=>s+=`<polygon points="${values.map((_,i)=>xy(i,95*f).join(',')).join(' ')}" fill="none" stroke="#ccb98b" stroke-width="1"/>`);values.forEach((v,i)=>{const p=xy(i,95),t=xy(i,125);s+=`<path d="M180 145L${p.join(' ')}" stroke="#d5c7a7"/><text x="${t[0]}" y="${t[1]}" text-anchor="middle" fill="#6c6041" font-size="11">${DATA.dimensions[i].name}<tspan x="${t[0]}" dy="15">${v}%</tspan></text>`});s+=`<polygon points="${values.map((v,i)=>xy(i,95*v/100).join(',')).join(' ')}" fill="#4f775b55" stroke="#6a8050" stroke-width="2"/>`;values.forEach((v,i)=>{const p=xy(i,95*v/100);s+=`<circle cx="${p[0]}" cy="${p[1]}" r="3" fill="#b69751"/>`});return s+'</svg>'}
function renderResult(r){lastResult=r;posterBlob=null;if(posterUrl)URL.revokeObjectURL(posterUrl);posterUrl=null;show('result');const p=r.primary;$('portrait').src=`characters/${p.id}.jpg`;$('portrait').alt=p.name+'人物肖像';for(const [id,value] of Object.entries({rName:p.name,rSub:p.subtitle,summary:p.summary,quote:p.quote,core:p.core,rel:p.relationships,love:p.love,work:p.workStyle,strength:p.tags.join('、')+'，是你值得珍惜的力量。'+p.summary,watch:p.watchOut}))$(id).textContent=value;$('tags').innerHTML=p.tags.map(t=>`<span class="tag">${t}</span>`).join('');$('advice').innerHTML=p.advice.map(a=>`<li>${a}</li>`).join('');$('matches').innerHTML=r.topMatches.map((m,i)=>`<div class="match"><img src="characters/${m.person.id}.jpg" alt="${m.person.name}"><div><small>0${i+1}</small><strong>${m.person.name}</strong><div class="meter"><i style="width:${m.similarity}%"></i></div></div><output>${m.similarity}%</output></div>`).join('');$('radar').innerHTML=radarSvg(r.scores);$('dimensions').innerHTML=DATA.dimensions.map((d,i)=>`<article class="dimension"><b>${d.name}</b><output>${r.scores[i]}%</output><span>${r.scores[i]>=50?d.high:d.low}</span><p>${d.description}</p></article>`).join('');$('posterArea').classList.add('hidden');$('posterMsg').textContent='';$('posterBtn').disabled=false}
$('again').onclick=()=>{show('lobby');start()};$('home').onclick=()=>show('lobby');
function loadImage(id){return new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>resolve(im);im.onerror=()=>reject(new Error('人物图片暂未加载成功，请检查网络后再试。'));im.src=`characters/${id}.jpg`})}
function wrap(ctx,text,x,y,width,line,max=20){let row='',lines=0;for(const ch of text){if(ctx.measureText(row+ch).width>width){ctx.fillText(row,x,y);row=ch;y+=line;if(++lines>=max)return y}else row+=ch}if(row)ctx.fillText(row,x,y);return y+line}
function cover(ctx,im,x,y,w,h){const scale=Math.max(w/im.width,h/im.height),sw=w/scale,sh=h/scale;ctx.drawImage(im,(im.width-sw)/2,(im.height-sh)/2,sw,sh,x,y,w,h)}
function makePoster(r,images){const c=document.createElement('canvas');c.width=1080;c.height=1440;const g=c.getContext('2d'),p=r.primary;g.fillStyle='#103a2d';g.fillRect(0,0,1080,1440);g.strokeStyle='#b99a59';g.lineWidth=2;g.strokeRect(20,20,1040,1400);g.strokeRect(28,28,1024,1384);const text=(s,x,y,size=24,color='#eddbaf',align='left')=>{g.fillStyle=color;g.font=`${size}px "SimSun",serif`;g.textAlign=align;g.fillText(s,x,y)};const panel=(x,y,w,h)=>{g.fillStyle='#f4ead2';g.fillRect(x,y,w,h);g.strokeStyle='#bc9d5e';g.lineWidth=3;g.strokeRect(x,y,w,h);g.lineWidth=1;g.strokeRect(x+6,y+6,w-12,h-12)};text('入 戏 · 甄 嬛 传 性 格 小 传',540,78,24,undefined,'center');text('不同的她们，也在你身上闪光',540,133,40,undefined,'center');text('你的人物光谱 · 不止一种你',540,178,21,undefined,'center');
panel(50,218,480,826);cover(g,images[0],59,227,462,616);g.fillStyle='#f4ead2';g.fillRect(59,780,462,255);text(p.name,290,840,58,'#354932','center');text(p.subtitle,290,881,25,'#6f5730','center');text(p.tags.join(' · '),290,929,23,'#8d723e','center');g.font='22px "SimSun",serif';g.fillStyle='#6d5c3d';g.textAlign='center';wrap(g,p.quote,290,976,405,31,2);
panel(550,218,480,378);text('Top 3 人物光谱',580,263,30,'#4b452f');r.topMatches.forEach((m,i)=>{const y=285+i*96;cover(g,images[i],574,y,69,79);text(m.person.name,664,y+29,27,'#51452d');text(m.similarity+'%',1003,y+34,27,'#68532d','right');g.fillStyle='#e1d2ae';g.fillRect(664,y+50,330,10);g.fillStyle='#8f9c63';g.fillRect(664,y+50,330*m.similarity/100,10)});
panel(550,616,480,428);text('六维性格倾向',580,661,30,'#4b452f');const cx=790,cy=842,rad=114;const xy=(i,r)=>[cx+Math.cos(-Math.PI/2+i*Math.PI/3)*r,cy+Math.sin(-Math.PI/2+i*Math.PI/3)*r];const poly=(radii,fill)=>{g.beginPath();radii.forEach((r,i)=>{const a=xy(i,r);i?g.lineTo(...a):g.moveTo(...a)});g.closePath();if(fill){g.fillStyle=fill;g.fill()}g.stroke()};g.strokeStyle='#c2af7e';[.25,.5,.75,1].forEach(f=>poly(Array(6).fill(rad*f)));for(let i=0;i<6;i++){g.beginPath();g.moveTo(cx,cy);g.lineTo(...xy(i,rad));g.stroke();const a=xy(i,rad+40);text(DATA.dimensions[i].name,a[0],a[1],19,'#6a5a35','center');text(r.scores[i]+'%',a[0],a[1]+24,17,'#977a40','center')}g.strokeStyle='#597349';g.lineWidth=2;poly(r.scores.map(v=>rad*v/100),'#66835166');
const scenes=[['性格底色',p.core],['人际关系',p.relationships],['亲密关系',p.love],['做事方式',p.workStyle]];scenes.forEach(([title,body],i)=>{const x=50+i*250;panel(x,1065,230,233);text(title,x+115,1109,26,'#69522e','center');g.font='21px "SimSun",serif';g.fillStyle='#6e6043';g.textAlign='left';const sentence=body.split(/[。；]/)[0];const shortened=sentence.length>44?sentence.slice(0,43)+'…':sentence+'。';wrap(g,shortened,x+18,1150,194,30,4)});text('人物是镜子，生活的主角始终是你。',540,1342,24,undefined,'center');text('娱乐性格测试 · 非专业心理诊断 · 相似度并非概率',540,1377,17,'#c8bb93','center');return c}
$('posterBtn').onclick=async()=>{if(!lastResult)return;const r=lastResult;$('posterBtn').disabled=true;$('posterMsg').textContent='正在装裱你的结果卡…';try{const images=await Promise.all(r.topMatches.map(m=>loadImage(m.person.id)));if(lastResult!==r)return;const canvas=makePoster(r,images);posterBlob=await new Promise(res=>canvas.toBlob(res,'image/png'));if(!posterBlob)throw new Error('生成失败，请重试。');if(posterUrl)URL.revokeObjectURL(posterUrl);posterUrl=URL.createObjectURL(posterBlob);$('poster').src=posterUrl;$('download').href=posterUrl;$('download').download=`入戏-${r.primary.name}-性格小传.png`;$('posterArea').classList.remove('hidden');$('posterMsg').textContent='结果卡已生成 · 1080 × 1440 高清图片';$('poster').scrollIntoView({behavior:'smooth',block:'start'})}catch(e){$('posterMsg').textContent=e.message||'图片生成失败，请稍后重试。'}finally{$('posterBtn').disabled=false}};
$('share').onclick=async()=>{if(!posterBlob)return;try{const file=new File([posterBlob],`入戏-${lastResult.primary.name}.png`,{type:'image/png'});if(navigator.canShare?.({files:[file]}))await navigator.share({files:[file],title:'我的甄嬛传性格小传'});else $('posterMsg').textContent='当前浏览器不支持直接分享，请下载或长按结果卡保存，再上传分享。'}catch(e){if(e.name!=='AbortError')$('posterMsg').textContent='暂未分享成功，可下载图片后手动分享。'}};
show(state.active?'lobby':'entry');
